### ISSUE TITLE
restrict resources access

### ISSUE THREAD

**Issue by bruno12mota** [relax/relax#96] opened 2015-10-15 18:12 UTC
Restrict resources for non admin users on GraphQL:

### Queries

- [x] pages list
- [x] draft page
- [x] schemas list
- [x] draft schema entries
- [x] menus list
- [x] media list
- [x] users list
- [x] user

### Mutations

- [x] all mutations

**Comment by magalhas** [comment] 2015-10-17 21:25
This is kind of done for the current implemented queries and mutations. We just need to keep in mind to call the `authorize` function in the new queries/mutations.

**Comment by magalhas** [comment] 2015-10-17 22:12
Also addUser mutation allows access if there are no users registered yet. Should we close this issue or use it as a reminder until we finish the refactoring?

**Comment by bruno12mota** [comment] 2015-10-18 12:52
we should check everything before closing

**Comment by magalhas** [comment] 2015-10-26 00:10
@bruno12mota `/api/media/resize` is as of now open to the public, I'm not sure if this is the intended behaviour. You can find this route inside server's public router.

**Comment by bruno12mota** [comment] 2015-10-26 08:14
Yes it is intended, public pages need to have a way to get images resized. It would though be nice to have a way of using an actual image url, so that it passes through nginx first and if not found, it would go through node to make the resized version. So that next time, nginx provides that resized image.

**Closed** 2015-11-06 14:08 UTC
Labels: refactor
