### ISSUE TITLE
Columns widget renders columns in separate rows in preview and live pages

### ISSUE THREAD

**Issue by mghaderyan-nisum-com** [relax/relax#430] opened 2017-03-16 23:18 UTC
steps to reproduce:
1) Add two columns next to each other in design mode.
2) Add a button in each. (you will see the columns in the same row)
3) click on "preview" or publish the page. You will see each button in a separate row

Design mode:
<img width="1228" alt="screen shot 2017-03-11 at 5 03 41 pm" src="https://cloud.githubusercontent.com/assets/15659166/24022510/27c98424-0a64-11e7-8f62-af7ecc303265.png">

Live mode:
<img width="1273" alt="screen shot 2017-03-11 at 5 03 57 pm" src="https://cloud.githubusercontent.com/assets/15659166/24022511/2a3b8eb4-0a64-11e7-9711-9ea1e635c53f.png">

**Comment by 4levels** [comment] 2017-05-05 12:27
This is a duplicate of #412 with quite some interesting investigation done by @slackjaw47 
Hoping someone can fix this issue soon as this is really a major element for layouting.

**Comment by bruno12mota** [comment] 2017-06-12 08:34
duplicate

**Closed by bruno12mota** 2017-06-12 08:34 UTC
